dist: Xenial
language: java
jdk:
 -openjdk8

addons:
  sonarcloud:
    organization: "klaigor"
    token:
      secure: "4797b663a1464ae493713b92bd53925eec91bdbf" # encrypted value of your token
  apt:
    packages:
        - ant       
script:
  - ant build
  - sonar-scanner
